[package]
name = "apicula"
version = "0.1.0"
authors = ["scurest <scurest@users.noreply.github.com>"]
license = "CC0-1.0"
build = "build.rs"

[dependencies]
cgmath = "0.16.0"
clap = "2.30.0"
env_logger = "0.5.3"
error-chain = "0.11.0"
glium = "0.16.0"
log = "0.4.1"
petgraph = "0.4.9"
png = "0.11.0"
regex = "0.2.6"
time = "0.1.36"

[profile.release]
panic = "abort"
lto = true
