[package]
name = "apicula"
version = "0.1.0"
authors = ["scurest <scurest@users.noreply.github.com>"]
license = "CC0-1.0"
build = "build.rs"

[dependencies]
cgmath = "0.14.1"
clap = "2.25.0"
env_logger = "0.4.3"
error-chain = "0.10.0"
glium = "0.16.0"
log = "0.3.8"
petgraph = "0.4.5"
png = "0.9.0"
regex = "0.2.1"
time = "0.1.36"
