[package]
name = "apicula"
version = "0.1.0"
authors = ["scurest <scurest@users.noreply.github.com>"]
license = "CC0-1.0"
build = "build.rs"

[dependencies]
cgmath = "0.12.0"
clap = "2.23.2"
env_logger = "0.4.2"
error-chain = "0.10.0"
glium = "0.16.0"
log = "0.3.7"
petgraph = "0.4.4"
png = "0.6.2"
regex = "0.2.1"
time = "0.1.36"
